spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 8081

logging:
  level:
    io.jjeom: DEBUG

---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  profiles: prod