server:
  port: 8081

spring:
  profiles:
    active: @spring.profiles.active@
  output:
    ansi:
      enabled: always

logging:
  level:
    io.jjeom: DEBUG

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/springboot
    username: jjeom
    password: a123456A
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      generate-ddl: true
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

---
spring:
  profiles: dev

---
spring:
  profiles: prod