server:
  port: 8081

spring:
  profiles:
    active: @spring.profiles.active@
  output:
    ansi:
      enabled: always

logging:
  level:
    io.jjeom: DEBUG
    org.hibernate.type.descriptor.sql: trace

pebble:
  suffix: .html
  cache: false
  exposeSessionAttributes: true
  exposeRequestAttributes: true

app:
  name: spring-boot-sampe-web

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/springboot
    username: springboot
    password: a123456A
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      generate-ddl: true
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost/springboot
    username: springboot
    password: a123456A
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        generate-ddl: true
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/springboot
    username: springboot
    password: a123456A
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        generate-ddl: true
        ddl-auto: validate
      properties:
        hibernate:
          format_sql: true